### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by PrakharSaxena24** [mianzhang/dialogue_gcn#6]
I am trying to use dialogueGCN for establishing baseline for my model, but I cannot run the code-
while executing     ./scripts/iemocap.sh train

Error:  RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:1 Long tensor

Error log-  
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main(args)
  File "train.py", line 35, in main
    ret = coach.train()
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/Coach.py", line 41, in train
    self.train_epoch(epoch)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/Coach.py", line 74, in train_epoch
    nll = self.model.get_loss(data)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/DialogueGCN.py", line 59, in get_loss
    graph_out, features = self.get_rep(data)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/DialogueGCN.py", line 43, in get_rep
    node_features = self.rnn(data["text_len_tensor"], data["text_tensor"]) # [batch_size, mx_len, D_g]
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/cudagcn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/SeqContext.py", line 20, in forward
    packed = pack_padded_sequence(
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/cudagcn/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 249, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:1 Long tensor

**Comment by PrakharSaxena24** [comment]
adding .cpu() to   dgcn/model/SeqContext.py  line 22 
                                                         
            text_len_tensor                                    ===>.        text_len_tensor.cpu()  

However it resulted in a new issue.    TypeError: forward() got an unexpected keyword argument 'edge_norm'

log-



Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main(args)
  File "train.py", line 35, in main
    ret = coach.train()
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/Coach.py", line 41, in train
    self.train_epoch(epoch)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/Coach.py", line 74, in train_epoch
    nll = self.model.get_loss(data)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/DialogueGCN.py", line 59, in get_loss
    graph_out, features = self.get_rep(data)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/DialogueGCN.py", line 48, in get_rep
    graph_out = self.gcn(features, edge_index, edge_norm, edge_type)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/cudagcn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/GCN.py", line 14, in forward
    x = self.conv1(node_features, edge_index, edge_type, edge_norm=edge_norm)
  File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/cudagcn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'edge_norm'


      please help

**Comment by mianzhang** [comment]
Please check your PyTorch version and PyTorch Geometric version.

**Comment by Yu-Fangxu** [comment]
> I am trying to use dialogueGCN for establishing baseline for my model, but I cannot run the code- while executing ./scripts/iemocap.sh train
> 
> Error: RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:1 Long tensor
> 
> Error log- Traceback (most recent call last): File "train.py", line 93, in main(args) File "train.py", line 35, in main ret = coach.train() File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/Coach.py", line 41, in train self.train_epoch(epoch) File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/Coach.py", line 74, in train_epoch nll = self.model.get_loss(data) File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/DialogueGCN.py", line 59, in get_loss graph_out, features = self.get_rep(data) File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/DialogueGCN.py", line 43, in get_rep node_features = self.rnn(data["text_len_tensor"], data["text_tensor"]) # [batch_size, mx_len, D_g] File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/cudagcn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/dgcn/model/SeqContext.py", line 20, in forward packed = pack_padded_sequence( File "/mnt/berry/home/prakhar/dialoguegcn/conv-emotion/DialogueGCN-mianzhang/cudagcn/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 249, in pack_padded_sequence _VF._pack_padded_sequence(input, lengths, batch_first) RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:1 Long tensor

Maybe you should try `text_len_tensor.cpu().to(torch.int64)`
